### PR TITLE
Adds Funding and CI implementation to development.

### PR DESCRIPTION
**Pull request by marickmanrho**
Unfortunately I think this is needed to make the CI work on the development branch. For example look at PR #143 which now doesn't have tests being run automatically.

### CODE REVIEW

**Comment by marickmanrho** [comment]
Fixes: #138

**Comment by Drvanon** [comment]
I am very confused: why are there two CI's? And why is one of them failing?

**Comment by marickmanrho** [comment]
When I try to reproduce this error on my device it is not always showing up. That might be the reason here to.

**Comment by marickmanrho** [comment]
Nevertheless I think we should merge this pull request. Then try to fix this by solving Issue #146

**Comment by Drvanon** [comment]
Noted.

**Pull request merged**
